### ISSUE TITLE
Microsphere nanojet simulation

### ISSUE THREAD

**Issue by Jason-code-source** [ovidiopr/scattnlay#19]
Hi! How can I increase the nmax in python code if I compute a large-scale (~ 10 wavelengths )sphere  ? I am looking forward to your reply! Thank you!

**Comment by kostyfisik** [comment]
You should use mp version of scattnlay , it will automatically increase
nmax to the needed value . In latest version on GitHub it is just the
parameter of function to run simulation.

**Comment by Jason-code-source** [comment]
Thank you! I am a bit confused by the mp scattnlay version you mentioned. Do you mean that I should install python-scattnlay_2.0.1-1_amd64.deb? Now, I am using the ovidiopr/scattnlay-5a74126 version and the value of nmax (default) is -1. But the mie code does not work well on computing the field around the large-scale model.

**Comment by kostyfisik** [comment]
Could you please provide the parameters of your model? I will try it myself.

**Comment by Jason-code-source** [comment]
Thanks for your reply, kostyfisik! My model is a dielectric sphere with a radius of 3 microns and refractive index of 1.33, exited by the plane wave with the wavelength of 532 nm. The backgroud is air. For more detail, please refer to the figure 1(d) in the paper _Control over parameters of photonic nanojets of dielectric microspheres_ (https://www.sciencedirect.com/science/article/abs/pii/S0030401810007431 ). Thanks again!

**Comment by Jason-code-source** [comment]
Thanks for your reply, kostyfisik! My model is a dielectric sphere with a radius of 5 microns and refractive index of 1.33, exited by the plane wave with the wavelength of 532 nm. The backgroud material is air. For more detail, please refer to the figure 1(d) in the paper _Control over parameters of photonic nanojets of dielectric microspheres_ (https://www.sciencedirect.com/science/article/abs/pii/S0030401810007431 ). Thanks again!

**Comment by kostyfisik** [comment]
@Jason-code-source I have coded the system, simulation script and results are in https://github.com/ovidiopr/scattnlay/tree/master/examples/Opt.Commun.-2010-Geints-Nanojets_of_dielectric_microspheres  It works well for the sphere of 0.5 mkm, OK for 1 mkm sphere with use of MP feature, and doesn`t work for larger sphres. @ovidiopr we may probably try to work on this in November.
Few result to compare against the paper:
![R0 5mkm_mp](https://user-images.githubusercontent.com/5239997/66934920-e8c1c980-f043-11e9-9ec7-051028d2b01d.jpg)
![R1mkm_mp](https://user-images.githubusercontent.com/5239997/66934921-e8c1c980-f043-11e9-9de1-5e6690937470.jpg)
![R3mkm_mp](https://user-images.githubusercontent.com/5239997/66934919-e8293300-f043-11e9-99e3-d7ab18ce2863.jpg)

**Comment by kostyfisik** [comment]
@Jason-code-source Now it works fine :) Just merged it into the master.
Note, that results from paper for near-field were incorrect. See comparision of updated scattnaly, paper, and Stratify code (the last has a colorbar on top). The result from Stratify and Scattnlay coincide inside the sphere. A bit away from the sphere Stratify has some problems. The result from the paper is similar, however, it is far from being precise both incide and outside the sphere
![Screenshot from 2021-04-28 18-29-25](https://user-images.githubusercontent.com/5239997/116436204-d473a500-a854-11eb-872a-70c8e0b04d4a.png)
![Screenshot from 2021-04-27 16-33-09](https://user-images.githubusercontent.com/5239997/116436245-e1909400-a854-11eb-8800-cb99e0f41435.png)
