### ISSUE TITLE
Fused silicon dioxide

### ISSUE THREAD

**Issue by RosyRuvalcaba** [ovidiopr/scattnlay#22]
Hi!
Could you add Fused silicon dioxide to the default list? the url from the refractiveindex.info is https://refractiveindex.info/?shelf=main&book=SiO2&page=Malitson

the simulator doesn´t let me add it 
thank you!!

**Comment by kostyfisik** [comment]
At the moment it is only possible to add data with both, n and k.
I will add it (substituting k with zeros), however, it will take some time to implement this feature, at the moment I am overloaded with other projects, sorry.
