### ISSUE TITLE
memory required

### ISSUE THREAD

**Issue by inzhevatkin** [ovidiopr/scattnlay#25]
Is it possible to estimate the amount of memory required when using standalone program fieldnlay.exe?

**Comment by kostyfisik** [comment]
I would estimate to have 800^3 (points) * 6 (filed components) * 4 (bytes per number for double precision) / 2^30 (GB) = 11.4Gb. Note, that you can write them to the drive as long as you process them.

**Comment by kostyfisik** [comment]
I've done some time ago, code is not ready to use, but you can get the idea from save_to_vtk.py file https://gist.github.com/kostyfisik/51914a358faeb739859d8e4a1db7ae39

**Comment by kostyfisik** [comment]
No response, closing.
