### ISSUE TITLE
Compilation issues for mac

### ISSUE THREAD

**Issue by joebiv98** [ovidiopr/scattnlay#69]
Hi,

I am trying to compile the code for python in Mac OS 14.2.1. I have installed boost c++ library as well and directed to the include directory for the resource files. At least from github it also says that all checks have failed as well.

- When running **pip install --global-option=build_ext --global-option="-I/opt/homebrew/Cellar/boost/1.83.0/include/" . --user** I encounter this error:

/Users/joebiv98/anaconda3/lib/python3.10/site-packages/setuptools/_distutils/dist.py:265: UserWarning: Unknown distribution option: 'extra_compile_args'
        warnings.warn(msg)
      In file included from src/nmie.cc:40:
      src/nmie.h:150:27: warning: default member initializer for non-static data member is a C++11 extension [-Wc++11-extensions]
          bool isExpCoeffsCalc_ = false;
                                ^
      src/nmie.h:151:27: warning: default member initializer for non-static data member is a C++11 extension [-Wc++11-extensions]
          bool isScaCoeffsCalc_ = false;
                                ^
      src/nmie.h:152:27: warning: default member initializer for non-static data member is a C++11 extension [-Wc++11-extensions]
          bool isMieCalculated_ = false;
                                ^
      src/nmie.h:156:29: warning: default member initializer for non-static data member is a C++11 extension [-Wc++11-extensions]
          int PEC_layer_position_ = -1;
                                  ^
      src/nmie.h:159:15: warning: default member initializer for non-static data member is a C++11 extension [-Wc++11-extensions]
          int nmax_ = -1;
                    ^
      src/nmie.h:160:22: warning: default member initializer for non-static data member is a C++11 extension [-Wc++11-extensions]
          int nmax_preset_ = -1;
                           ^
      src/nmie.h:166:18: warning: default member initializer for non-static data member is a C++11 extension [-Wc++11-extensions]
          double Qsca_ = 0.0, Qext_ = 0.0, Qabs_ = 0.0, Qbk_ = 0.0, Qpr_ = 0.0, asymmetry_factor_ = 0.0, albedo_ = 0.0;
                       ^
      src/nmie.h:166:31: warning: default member initializer for non-static data member is a C++11 extension [-Wc++11-extensions]
          double Qsca_ = 0.0, Qext_ = 0.0, Qabs_ = 0.0, Qbk_ = 0.0, Qpr_ = 0.0, asymmetry_factor_ = 0.0, albedo_ = 0.0;
                                    ^
      src/nmie.h:166:44: warning: default member initializer for non-static data member is a C++11 extension [-Wc++11-extensions]
          double Qsca_ = 0.0, Qext_ = 0.0, Qabs_ = 0.0, Qbk_ = 0.0, Qpr_ = 0.0, asymmetry_factor_ = 0.0, albedo_ = 0.0;
                                                 ^
      src/nmie.h:166:56: warning: default member initializer for non-static data member is a C++11 extension [-Wc++11-extensions]
          double Qsca_ = 0.0, Qext_ = 0.0, Qabs_ = 0.0, Qbk_ = 0.0, Qpr_ = 0.0, asymmetry_factor_ = 0.0, albedo_ = 0.0;
                                                             ^
      src/nmie.h:166:68: warning: default member initializer for non-static data member is a C++11 extension [-Wc++11-extensions]
          double Qsca_ = 0.0, Qext_ = 0.0, Qabs_ = 0.0, Qbk_ = 0.0, Qpr_ = 0.0, asymmetry_factor_ = 0.0, albedo_ = 0.0;
                                                                         ^
      src/nmie.h:166:93: warning: default member initializer for non-static data member is a C++11 extension [-Wc++11-extensions]
          double Qsca_ = 0.0, Qext_ = 0.0, Qabs_ = 0.0, Qbk_ = 0.0, Qpr_ = 0.0, asymmetry_factor_ = 0.0, albedo_ = 0.0;
                                                                                                  ^
      src/nmie.h:166:108: warning: default member initializer for non-static data member is a C++11 extension [-Wc++11-extensions]
          double Qsca_ = 0.0, Qext_ = 0.0, Qabs_ = 0.0, Qbk_ = 0.0, Qpr_ = 0.0, asymmetry_factor_ = 0.0, albedo_ = 0.0;
                                                                                                                 ^
      src/nmie.cc:293:10: warning: 'auto' type specifier is a C++11 extension [-Wc++11-extensions]
          for (auto f:E)
               ^
      src/nmie.cc:293:16: warning: range-based for loop is a C++11 extension [-Wc++11-extensions]
          for (auto f:E)
                     ^
      src/nmie.cc:296:10: warning: 'auto' type specifier is a C++11 extension [-Wc++11-extensions]
          for (auto f:H)
               ^
      src/nmie.cc:296:16: warning: range-based for loop is a C++11 extension [-Wc++11-extensions]
          for (auto f:H)
                     ^
      src/nmie.cc:304:29: error: expected expression
            ml_mie.SetFieldCoords({Xp_vec, Yp_vec, Zp_vec});
                                  ^
      src/nmie.cc:426:10: warning: 'auto' type specifier is a C++11 extension [-Wc++11-extensions]
          for (auto curr_layer_size : layer_size) {
               ^
      src/nmie.cc:426:31: warning: range-based for loop is a C++11 extension [-Wc++11-extensions]
          for (auto curr_layer_size : layer_size) {
                                    ^
      src/nmie.cc:1003:25: warning: comparison of integers of different signs: 'int' and 'size_type' (aka 'unsigned long') [-Wsign-compare]
            for (int t = 0; t < theta_.size(); t++) {
                            ~ ^ ~~~~~~~~~~~~~
      src/nmie.cc:1080:5: warning: 'auto' type specifier is a C++11 extension [-Wc++11-extensions]
          auto& m = refractive_index_;
          ^
      src/nmie.cc:1168:40: error: non-aggregate type 'std::vector<std::complex<double> >' cannot be initialized with an initializer list
          std::vector<std::complex<double> > ipow = {c_one, c_i, -c_one, -c_i}; // Vector containing precomputed integer powers of i to avoid computation
                                             ^      ~~~~~~~~~~~~~~~~~~~~~~~~~~
      src/nmie.cc:1265:10: warning: 'auto' type specifier is a C++11 extension [-Wc++11-extensions]
          for (auto& f : E_) f.resize(3);
               ^
      src/nmie.cc:1265:18: warning: range-based for loop is a C++11 extension [-Wc++11-extensions]
          for (auto& f : E_) f.resize(3);
                       ^
      src/nmie.cc:1266:10: warning: 'auto' type specifier is a C++11 extension [-Wc++11-extensions]
          for (auto& f : H_) f.resize(3);
               ^
      src/nmie.cc:1266:18: warning: range-based for loop is a C++11 extension [-Wc++11-extensions]
          for (auto& f : H_) f.resize(3);
                       ^
      25 warnings and 2 errors generated.
      error: command '/usr/bin/clang' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed cleaning build dir for python-scattnlay
Failed to build python-scattnlay
ERROR: Could not build wheels for python-scattnlay, which is required to install pyproject.toml-based projects

My python version is 3.10.11, and my pip installer is 23.3.2. Any advice would be much appreciated! Thank you.

**Comment by kostyfisik** [comment]
Hmm... It seems that in modern systems it requires explicit c++11 compilation flag. Added this to setup.py, it works fine for latest Ubuntu in CI\CD pipeline and on my MacOS 14.2.1 with Apple Silicon (arm64). Please, try latest master. 

BTW, note that boost is an optional requirement, few years ago we had updated computational core, now it manages rather tricky models in standard (double) precision just fine...
