### ISSUE TITLE
errors when trying to install scattnlay in Mac

### ISSUE THREAD

**Issue by rofenollo** [ovidiopr/scattnlay#76]
In Mac M2 Ventura 13.6.1 (Xcode version is 15.2), I got many errors when executing in the terminal:

python3 -m pip install python-scattnlay-2.3.tar.gz

/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/cmath:607:12: error: no matching function for call to 'isinf'

/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/cmath:587:12: error: no matching function for call to 'isnan'

/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/complex:637:19: error: no matching function for call to '__constexpr_copysign'

 /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/complex:638:19: error: no matching function for call to '__constexpr_copysign'

/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/complex:706:63: error: no matching function for call to '__constexpr_fabs'

/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/cmath:627:31: error: floating point classification requires argument of floating point type (passed in 'boost::multiprecision::number<boost::multiprecision::backends::cpp_bin_float<100>>')

/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/complex:762:19: error: no matching function for call to '__constexpr_copysign'

fatal error: too many errors emitted, stopping now [-ferror-limit=]
      2 warnings and 20 errors generated.
      error: command '/usr/bin/clang' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for python-scattnlay

**Comment by kostyfisik** [comment]
2.3 was released (and packed) few years ago and seems to be not very compatible with modern compilers and it was never tested for Mac. Modern version of scattnlay is compatible with Linux, WIndows, and Mac (which is part of CI\CD now). Could you please try to install latest version: 
```
git clone https://github.com/ovidiopr/scattnlay.git
cd scattnlay
pip3 install --user .
```

**Comment by rofenollo** [comment]
Thank you very much Konstantin, now it works!!
