### ISSUE TITLE
size parameter should be a complex variable to deal with lossy host media.

### ISSUE THREAD

**Issue by kostyfisik** [ovidiopr/scattnlay#8]

**Comment by ovidiopr** [comment]
This is not so easy. The classical derivation of Mie theory is for a non-absorbing medium. For an absorbing matrix you need a different derivation:

1. Qiang Fu and Wenbo Sun, "Mie theory for light scattering by a spherical particle in an absorbing medium," Appl. Opt. 40, 1354-1361 (2001)
